version: '2'
services:
  applications:
    build: 
      context: ./docker-containers/applications
    volumes:
      - ./www-workspace:/var/www:cached

  workspace:
    build:
      context: ./docker-containers/workspace
    # environment:
      # app stuff
      # - DATABASE_NAME=${DATABASE_NAME}
      # - DB_HOST=${MYSQL_HOST}
      # - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_USER=${MYSQL_USER}
    volumes_from:
      - applications
    ports:
      - "4200:4200"
    depends_on: [mysql, applications]

  php-fpm:
    build:
      context: ./docker-containers/php-fpm
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DB_HOST=${MYSQL_HOST}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
    volumes_from:
      - applications
    expose:
      - "9000"

  nginx:
      build:
          context: ./docker-containers/nginx
          args:
          - PHP_UPSTREAM=php-fpm
      volumes_from:
          - applications
      volumes:
          - ./docker-containers/nginx/sites:/etc/nginx/sites-available
      ports:
          - "80:80"
          - "443:443"
      depends_on: [php-fpm, mysql]

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    build: ./docker-containers/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      - PMA_HOST=${MYSQL_HOST}
    ports:
      - "8080:80"
    depends_on:
      - "mysql"

### Volumes Setup ###

volumes:
  phpmyadmin:
    driver: "local"
  mysqldata:
    driver: "local"
